# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0002_cheeriodance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=128)),
                ('etc', models.CharField(max_length=512)),
            ],
        ),
    ]
