# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-13 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0004_auto_20170914_0526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
