# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0006_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kr', models.CharField(max_length=24)),
                ('name_en', models.CharField(max_length=64)),
                ('score_kr', models.CharField(max_length=24)),
                ('score_ys', models.CharField(max_length=24)),
                ('updated_titme', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
