# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0007_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('location', models.CharField(max_length=120)),
            ],
        ),
    ]
